baseURL: https://blog.imlk.top/
languageCode: zh-cn
title: imlk's blog
hasCJKLanguage: true 
buildDrafts: false

# ignore files under `content/` fir
ignoreFiles:
  - 'posts/images'
  - 'posts/objects'
  - 'images'
  - 'objects'

# each taxonomies in this form:
#   singular value: plural value
taxonomies:
  category: categories
  tag: tags

disableKinds:
  - taxonomyTerm

enableGitInfo: true

menu:
  main:
    - name: ğŸ Home
      url: ""
      weight: 1
    - name: ğŸ‘‹About
      url: "about/"
      weight: 2
    - name: ğŸ“œArchives
      url: "archives/"
      weight: 3
    - name: ğŸ”—Friends
      url: "friends/"
      weight: 5
    - name: ğŸ•¸ï¸DN42
      url: "dn42/"
      weight: 6
    - name: ğŸ“¢Subscribe
      url: "index.xml"
      weight: 7
    # TODO: consider add a page to show my toy boxes here??
    # TODO: add a page for guests to leave some message. may be encrypted message can be supported


params:
  footer: "&copy; imlk 2017 -- 2023 | [imlk\\'s blog](https://blog.imlk.top) | [Github](https://github.com/KB5201314/) | [Email](mailto:me@imlk.top) | [äº¬ICPå¤‡ - 2020042968å·](https://beian.miit.gov.cn/)"
  utteranc:
    enable: true
    repo: "KB5201314/KB5201314.github.io"
    issueTerm: "pathname"
    theme: "github-light"
    label: "ğŸ’¬ comments ğŸ’¬"

markup:
  goldmark:
    renderer:
      unsafe: true

